import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
// 按需引入
import {
  create,
  NButton,
  NCard,
  NTabs,
  NTabPane,
  NForm,
  NFormItemRow,
  NInput,
  NSpace,
  NLayout,
  NLayoutContent,
  NLayoutFooter,
  NLayoutHeader,
  NLayoutSider,
  NAnchor,
  NAnchorLink,
  NMenu,
  NIcon,
  NConfigProvider,
  NBreadcrumb,
  NBreadcrumbItem,
  NAvatar,
  NPopover,
  NPopconfirm,
  NListItem,
  NList,
  NModal,
  NUpload,
  NThing,
  NRow,
  NCol,
  NStatistic,
  NDataTable,
  NMessageProvider,
  NLoadingBarProvider,
  NResult,
  NImage,
  NSwitch,
  NGrid,
  NGi,
  NDropdown,
  NGradientText,
} from 'naive-ui';
import './assets/font/iconfont/iconfont.css';
import 'normalize.css';
import lazyPlugin from 'vue3-lazy';

const naive = create({
  components: [
    NButton,
    NCard,
    NTabs,
    NTabPane,
    NForm,
    NFormItemRow,
    NInput,
    NSpace,
    NLayout,
    NLayoutContent,
    NLayoutFooter,
    NLayoutHeader,
    NLayoutSider,
    NAnchor,
    NAnchorLink,
    NMenu,
    NIcon,
    NConfigProvider,
    NBreadcrumb,
    NBreadcrumbItem,
    NAvatar,
    NPopover,
    NPopconfirm,
    NList,
    NListItem,
    NModal,
    NUpload,
    NThing,
    NRow,
    NCol,
    NStatistic,
    NDataTable,
    NMessageProvider,
    NLoadingBarProvider,
    NMessageProvider,
    NResult,
    NImage,
    NSwitch,
    NGrid,
    NGi,
    NDropdown,
    NGradientText,
  ],
});

const app = createApp(App);
app.use(lazyPlugin, {
  loading: require('assets/svg/orange.progress-bar-stripe-loader.svg'),
  error: require('assets/img/article-my.png'),
});
app.use(naive).use(store).use(router).mount('#app');
